### ISSUE TITLE
IDA Capstone Feedback

### ISSUE THREAD

**Issue by mackenzieyoung** [jon-ayala/intro-data-musclehub-capstone#1]
## Rubric Score
 
### Criteria 1: Presentation: Are all required slides present?
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Great job, all the requirements are met in the analysis document. Your slides are very well-designed and easy to read.
 
### Criteria 2: Code Accuracy: Does the Python code do what it is supposed to?
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Very good, your code accurately retrieves the data intended.
 
### Criteria 3: Understanding hypothesis testing and interpreting the p-value
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ You did a nice job stating the hypothesis, stating the results, accepting/rejecting the hypothesis based on your results, and interpreting the hypothesis outcome. The only small change I would make would be to leave the p-values as decimals instead of converting them to percents. It's not typical to write p-values as percents.
 
### Criteria 4: Ability to interpret the Objective & Outcome of the analysis in context
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Good job, your objective and recommendation / conclusion slides meet the requirements.

 ### Overall Score: 16/16
Excellent work!

**Comment by jon-ayala** [comment]
Thank you for your feedback!
